stages:
  preprocess:
    cmd: python3 src/data_cleaning.py # data/raw/bike_sharing_modified.csv data/processed/bike_sharing_cleaned.csv
    deps:
      - src/data_cleaning.py
      - data/raw/bike_sharing_modified.csv
    # outs:
      # - data/processed/bike_sharing_cleaned.csv

  split_data:
    cmd: python3 src/DataSplit.py
    deps:
      - src/DataSplit.py
      - data/processed/bike_sharing_cleaned.csv
    # outs:
    #   - data/processed/test.csv
    #   - data/processed/train.csv
    #   - data/processed/valid.csv
