stages:
  preprocess:
    cmd: uv run src/data_cleaning.py
    deps:
      - src/data_cleaning.py
      - data/raw/bike_sharing_modified.csv
    outs:
      - data/processed/bike_sharing_cleaned.csv

  split_data:
    cmd: uv run src/data_split.py
    deps:
      - src/data_split.py
      - data/processed/bike_sharing_cleaned.csv
    outs:
      - data/processed/test.csv
      - data/processed/train.csv
      - data/processed/valid.csv

  train:
    cmd: uv run src/train_models.py config/models_config.yaml
    deps:
      - src/train_models.py
      - config/models_config.yaml
      - data/processed/train.csv
      - data/processed/valid.csv
      - data/processed/test.csv
    params:
      - config/models_config.yaml:
          - models
          - mlflow.experiment_name
    outs:
      - models/modelo_linear_regression.pickle
      - models/modelo_ridge_regression.pickle
      - models/modelo_lasso_regression.pickle
      - models/modelo_elasticnet.pickle
      - models/modelo_xgboost.pickle
    metrics:
      - models/model_comparison.csv:
          cache: false

  test:
    cmd: uv run pytest tests/ -v
    deps:
      - tests/test_data_cleaning.py
      - tests/test_data_split.py
      - tests/test_clean_utils.py
      - tests/test_pipeline_integration.py
      - tests/test_imports.py
      - src/data_cleaning.py
      - src/data_split.py
      - src/clean_utils.py
      - pytest.ini
